### ISSUE TITLE
New: linesandplanes-vectorequation

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/Open-LA-Applets#45] opened 2023-02-28 13:39 UTC
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#fig-linesandplanes-vectorequation

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/72745426/221869156-a67fba74-502e-4387-b3bf-b4c8b8108962.png)

### Requirements

See definition 1.13, formula must show this definition to show r

### What elements are interactive?

This image must be split into two applets.
In the first you shouldbe able to change the multiplier r, which will change the length of u, which shows that L = the vector equation for all values of r.
In the second you should be able to move the end of v0 over the line (and have u move with it), to show that L can be represented by different v0s that end in the correct poistion.

**Comment by yustarandomname** [comment] 2024-08-23 07:20
Close because it is a duplicate of #100

**Closed by yustarandomname** 2024-08-23 07:20 UTC
Labels: new applet
