### ISSUE TITLE
[New image]: changeofbasis-projection

### ISSUE THREAD

**Issue by juliavdkris** [PRIME-TU-Delft/Open-LA-Applets#90] opened 2023-04-26 14:52 UTC
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter4/ChangeOfBasis.html#fig-changeofbasis-projection

### What type of applet is this?

Interactive applet 3D

### Link to applet

https://openla.ewi.tudelft.nl/applet/change_of_basis/projection

### What state is the static image?

Yes, Dennis has created a static image

### Static image

![image](https://user-images.githubusercontent.com/22723225/234614619-11318c42-b1cc-41c1-bb3e-1cdeead3401b.png)

### Requirements

None

### Steps to completion:

- [X] assign yourself & check labels
- [X] implement new applet described above
- [ ] embed the image in the book (with review status)
- [ ] get feedback from the math teachers
- [ ] get feedback from writers
- [ ] remove review status in book

**Comment by ChristopheTUD** [comment] 2023-05-11 08:20
x,y,z
b1, b2, b3: the numbers are indices, should be in subscript
I don't get the meaning of the pink lines and the green vectors. Were they meant to show that there is a change of basis first, from e1, e2, e3 to b1, b2, b3? Then those green vectors seem wrong (and then I would also expect three of them, rather than two).

**Comment by yustarandomname** [comment] 2024-08-29 10:24
duplicate of #66. It is better described there. This issue is thus closed

**Closed by yustarandomname** 2024-08-29 10:24 UTC
Labels: change required
